### ISSUE TITLE
Fix link to Research IT training, once we have a suitable landing page for it

### ISSUE THREAD

**Issue by anenadic** [UoMResearchIT/carpentries-manchester#6]
On home page and secondary navigation tab too

**Comment by gcapes** [comment]
The black navigation bar's link to Research IT Training points to http://www.itservices.manchester.ac.uk/research/ which doesn't mention training. It should probably point here instead: http://www.staffnet.manchester.ac.uk/staff-learning-and-development/academicandresearch/practical-skills-and-knowledge/it-skills/research-computing/research-courses/

**Comment by anenadic** [comment]
Closing via 247d8eab749507ede34a9803590531c554534059.
